--- !ditz.rubyforge.org,2008-03-06/project 
name: towerdefence
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: gfx
- !ditz.rubyforge.org,2008-03-06/component 
  name: awt
- !ditz.rubyforge.org,2008-03-06/component 
  name: android
- !ditz.rubyforge.org,2008-03-06/component 
  name: usability
releases: []

